/////////////////////////////////////////////////////////////////////
////
//// AUTOGENERATED FILE - DO NOT EDIT
//// DRM SCRIPT VERSION 2.0.0
//// DRM HDK VERSION 3.2.2.0
//// DRM VERSION 3.2.2
//// COPYRIGHT (C) ALGODONE
////
/////////////////////////////////////////////////////////////////////

// the following constant contains the activation code value.
`define C_DRM_ACTIVATION_CODE 128'h8D7471B1462EF2B0159661F6A532861B
