---------------------------------------------------------------------
----
---- AUTOGENERATED FILE - DO NOT EDIT
---- DRM SCRIPT VERSION 2.0.0
---- DRM HDK VERSION 3.2.2.0
---- DRM VERSION 3.2.2
---- COPYRIGHT (C) ALGODONE
----
---------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;

package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00030001 is

  -- the following constant contains the activation code value.
  constant C_DRM_ACTIVATION_CODE : std_logic_vector(127 downto 0) := x"8D7471B1462EF2B0159661F6A532861B";

end package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00030001;