---------------------------------------------------------------------
----
---- AUTOGENERATED FILE - DO NOT EDIT
---- DRM SCRIPT VERSION 2.0.0
---- DRM HDK VERSION 3.2.2.0
---- DRM VERSION 3.2.2
---- COPYRIGHT (C) ALGODONE
----
---------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;

package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00010001 is

  -- the following constant contains the activation code value.
  constant C_DRM_ACTIVATION_CODE : std_logic_vector(127 downto 0) := x"7E745E528F0CF2F36C304A2F18DB0CE0";

end package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00010001;