---------------------------------------------------------------------
----
---- AUTOGENERATED FILE - DO NOT EDIT
---- DRM SCRIPT VERSION 2.0.0
---- DRM HDK VERSION 3.2.2.0
---- DRM VERSION 3.2.2
---- COPYRIGHT (C) ALGODONE
----
---------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;

package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00050001 is

  -- the following constant contains the activation code value.
  constant C_DRM_ACTIVATION_CODE : std_logic_vector(127 downto 0) := x"1C61CF7238D5D2FD7D82F5C697D753B1";

end package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00050001;