/////////////////////////////////////////////////////////////////////
////
//// AUTOGENERATED FILE - DO NOT EDIT
//// DRM SCRIPT VERSION 2.0.0
//// DRM HDK VERSION 3.2.2.0
//// DRM VERSION 3.2.2
//// COPYRIGHT (C) ALGODONE
////
/////////////////////////////////////////////////////////////////////

// the following constant contains the activation code value.
`define C_DRM_ACTIVATION_CODE 128'h1C61CF7238D5D2FD7D82F5C697D753B1
