---------------------------------------------------------------------
----
---- AUTOGENERATED FILE - DO NOT EDIT
---- DRM SCRIPT VERSION 2.0.0
---- DRM HDK VERSION 3.2.2.0
---- DRM VERSION 3.2.2
---- COPYRIGHT (C) ALGODONE
----
---------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;

package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00020001 is

  -- the following constant contains the activation code value.
  constant C_DRM_ACTIVATION_CODE : std_logic_vector(127 downto 0) := x"EE1241B2D99AD5EE56C713B6D45FF06B";

end package DRM_ACTIVATION_CODE_PACKAGE_0x1003000E00020001;